version: '3.8'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - the_net
  docs_api:
    build: ./
    ports:
    - 5050:5050
    environment:
    - sql_db=sqlite:///database.db
    - host_elastic=http://es:9200
    depends_on:
      - es
    networks:
      - the_net
networks:
  the_net: